build:
  maxIssues: 0
  excludeCorrectable: false
config:
  validation: true
complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
style:
  MagicNumber:
    active: false
