#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_PROPERTIES_FILE="$ROOT_DIR/local.properties"

decode_local_properties_value() {
  local value="$1"
  value="${value//\\:/:}"
  value="${value//\\\\/\\}"
  value="${value//\\ / }"
  printf "%s" "$value"
}

is_valid_sdk_dir() {
  local sdk_dir="$1"
  [ -d "$sdk_dir" ] && (
    [ -d "$sdk_dir/platform-tools" ] ||
      [ -d "$sdk_dir/cmdline-tools" ] ||
      [ -d "$sdk_dir/platforms" ]
  )
}

detect_local_properties_sdk() {
  if [ ! -f "$LOCAL_PROPERTIES_FILE" ]; then
    return 1
  fi

  local sdk_line=""
  sdk_line="$(grep -E '^sdk\.dir=' "$LOCAL_PROPERTIES_FILE" | tail -n 1 || true)"
  if [ -z "$sdk_line" ]; then
    return 1
  fi

  local raw_value="${sdk_line#sdk.dir=}"
  local decoded_value
  decoded_value="$(decode_local_properties_value "$raw_value")"
  if is_valid_sdk_dir "$decoded_value"; then
    printf "%s" "$decoded_value"
    return 0
  fi

  return 1
}

detect_sdk() {
  local candidates=()

  if [ -n "${ANDROID_HOME:-}" ]; then
    candidates+=("$ANDROID_HOME")
  fi
  if [ -n "${ANDROID_SDK_ROOT:-}" ]; then
    candidates+=("$ANDROID_SDK_ROOT")
  fi

  local local_props_sdk=""
  local_props_sdk="$(detect_local_properties_sdk || true)"
  if [ -n "$local_props_sdk" ]; then
    candidates+=("$local_props_sdk")
  fi

  case "$(uname -s)" in
    Darwin*)
      candidates+=("$HOME/Library/Android/sdk")
      ;;
    Linux*)
      candidates+=(
        "$HOME/Android/Sdk"
        "$HOME/Android/sdk"
        "/usr/local/android-sdk"
        "/opt/android-sdk"
      )
      ;;
    MINGW*|MSYS*|CYGWIN*)
      if command -v cmd.exe >/dev/null 2>&1; then
        local localappdata_windows=""
        localappdata_windows="$(cmd.exe /c "echo %LOCALAPPDATA%" 2>/dev/null | tr -d '\r' || true)"
        if [ -n "$localappdata_windows" ]; then
          if command -v cygpath >/dev/null 2>&1; then
            candidates+=("$(cygpath -u "$localappdata_windows")/Android/Sdk")
          fi
          candidates+=("$localappdata_windows/Android/Sdk")
        fi
      fi
      ;;
  esac

  # Common WSL/Git-Bash fallback paths.
  local user_name="${USERNAME:-${USER:-}}"
  if [ -n "$user_name" ]; then
    candidates+=(
      "/mnt/c/Users/$user_name/AppData/Local/Android/Sdk"
      "/c/Users/$user_name/AppData/Local/Android/Sdk"
    )
  fi

  local candidate=""
  for candidate in "${candidates[@]}"; do
    [ -n "$candidate" ] || continue
    if is_valid_sdk_dir "$candidate"; then
      printf "%s" "$candidate"
      return 0
    fi
  done

  return 1
}

write_local_properties_sdk() {
  local sdk_dir="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  if [ -f "$LOCAL_PROPERTIES_FILE" ]; then
    awk -v sdk_dir="$sdk_dir" '
      BEGIN { updated = 0 }
      /^sdk\.dir=/ {
        if (!updated) {
          print "sdk.dir=" sdk_dir
          updated = 1
        }
        next
      }
      { print }
      END {
        if (!updated) {
          print "sdk.dir=" sdk_dir
        }
      }
    ' "$LOCAL_PROPERTIES_FILE" >"$tmp_file"
  else
    {
      echo "# Auto-generated by scripts/ensure-android-sdk.sh"
      echo "sdk.dir=$sdk_dir"
    } >"$tmp_file"
  fi

  mv "$tmp_file" "$LOCAL_PROPERTIES_FILE"
}

main() {
  local sdk_dir=""
  if ! sdk_dir="$(detect_sdk)"; then
    echo "Unable to detect Android SDK path." >&2
    echo "Set ANDROID_HOME or ANDROID_SDK_ROOT, or create $LOCAL_PROPERTIES_FILE with sdk.dir=<path>." >&2
    exit 1
  fi

  write_local_properties_sdk "$sdk_dir"
  echo "Android SDK configured: $sdk_dir"
  echo "Updated: $LOCAL_PROPERTIES_FILE"
}

main "$@"
